/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file reprojection_factor_batch_test.cpp
 * @brief Unit tests for ReprojectionFactorBatch.
 *
 * Tests the reprojection factor by creating synthetic 3D points and
 * camera poses, projecting points to create observations in normalized
 * coordinates, then verifying that optimization can recover disturbed
 * states (either points or poses).
 */

#include "cunls/factor/reprojection_factor_batch.h"

#include <gtest/gtest.h>

#include <cmath>
#include <random>
#include <vector>

#include "cunls/common/cublas_helper.h"
#include "cunls/common/cuda_stream.h"
#include "cunls/minimizer/gauss_newton_minimizer.h"
#include "cunls/common/helper.h"
#include "cunls/minimizer/levenberg_marquardt_minimizer.h"
#include "cunls/math/lie_math.h"
#include "cunls/minimizer/problem.h"
#include "cunls/common/profiler.h"
#include "cunls/state/se3_state_batch.h"
#include "cunls/common/types.h"
#include "cunls/state/vector_state_batch.h"

namespace cunls {

/// Default z_threshold for reprojection: minimum depth for valid projection
constexpr float kDefaultZThreshold = 1e-3f;

/// Minimum required depth in camera frame for a valid projection
constexpr float kMinDepth = 1.0f;

/**
 * @brief Test fixture for ReprojectionFactorBatch unit tests.
 *
 * This fixture creates a synthetic bundle adjustment scenario:
 * - Multiple camera poses (SE3 transforms)
 * - Multiple 3D points in world coordinates
 * - Each pose observes a subset of points
 * - Observations are generated by projecting points through poses
 *   in NORMALIZED coordinates (no camera intrinsics)
 *
 * The tests verify that:
 * 1. Disturbed 3D points can be recovered through optimization
 * 2. Disturbed camera poses can be recovered through optimization
 */
class ReprojectionFactorBatchTest : public ::testing::Test {
 public:
  /// Point type: 3D world coordinates
  using Point3D = Vector<3>;

  /// Observation type: 2D normalized image coordinates
  using Observation2D = Vector<2>;

  void SetUp() override {
    // Initialize random number generator with fixed seed for reproducibility
    std::mt19937 rng(fixed_seed_);
    std::uniform_real_distribution<float> rotation_dist(-0.3f, 0.3f);
    std::uniform_real_distribution<float> translation_dist(-1.0f, 1.0f);
    std::uniform_real_distribution<float> point_dist(-3.0f, 3.0f);

    // Generate random camera poses looking at the origin from a distance
    GenerateRandomPoses(num_poses_, rng, rotation_dist, translation_dist,
                        ground_truth_poses_);

    // Generate random 3D points ensuring they are visible from all cameras
    GenerateRandomPointsVisibleFromAllCameras(num_points_, rng, point_dist,
                                              ground_truth_points_);

    // Validate that all points are in front of all cameras
    ValidateAllPointsVisible();

    // Generate observations by projecting points through poses
    // Each pose observes all points (for simplicity)
    GenerateObservations();
  }

 protected:
  /**
   * @brief Computes the depth (z coordinate) of a point in camera frame.
   *
   * Transforms the point to camera coordinates and returns the z component.
   * Positive z means the point is in front of the camera.
   *
   * @param pose SE3 camera pose (world-to-camera transform)
   * @param point 3D point in world coordinates
   * @return Z coordinate in camera frame (positive = in front of camera)
   */
  float ComputePointDepth(const SE3Transform& pose, const Point3D& point) {
    // P_cam.z = R[2,:] * P + t.z
    float depth = pose[2 * 4 + 3];  // tz
    for (int j = 0; j < 3; j++) {
      depth += pose[2 * 4 + j] * point[j];
    }
    return depth;
  }

  /**
   * @brief Validates that all points are visible from all cameras.
   *
   * Checks that every point has positive depth (z > kMinDepth) when
   * transformed to every camera's coordinate frame.
   *
   * @throws std::runtime_error if any point is behind any camera
   */
  void ValidateAllPointsVisible() {
    for (size_t pose_idx = 0; pose_idx < ground_truth_poses_.size();
         pose_idx++) {
      for (size_t point_idx = 0; point_idx < ground_truth_points_.size();
           point_idx++) {
        float depth = ComputePointDepth(ground_truth_poses_[pose_idx],
                                        ground_truth_points_[point_idx]);
        if (depth < kMinDepth) {
          throw std::runtime_error("Point " + std::to_string(point_idx) +
                                   " has depth " + std::to_string(depth) +
                                   " < " + std::to_string(kMinDepth) +
                                   " in camera " + std::to_string(pose_idx));
        }
      }
    }
  }

  /**
   * @brief Generates random SE3 camera poses looking at the origin.
   *
   * Creates random SE3 transformation matrices representing camera poses.
   * Cameras are positioned around the origin at a fixed distance, looking
   * towards the origin. Small random perturbations are applied.
   *
   * @param num_poses Number of poses to generate
   * @param rng Random number generator
   * @param rotation_dist Distribution for rotation perturbations
   * @param translation_dist Distribution for translation perturbations
   * @param poses Output vector of SE3 transforms
   */
  void GenerateRandomPoses(
      size_t num_poses, std::mt19937& rng,
      std::uniform_real_distribution<float>& rotation_dist,
      std::uniform_real_distribution<float>& translation_dist,
      std::vector<SE3Transform>& poses) {
    // Generate random twists and convert to SE3
    // Cameras are placed at distance ~10 from origin, looking at origin
    hvector<Vector<6>> twists(num_poses);
    for (size_t i = 0; i < num_poses; i++) {
      Vector<6>& twist = twists[i];
      // Small rotation perturbations
      twist[0] = rotation_dist(rng);  // rotation x
      twist[1] = rotation_dist(rng);  // rotation y
      twist[2] = rotation_dist(rng);  // rotation z
      // Translation: camera positioned such that origin is ~10 units in front
      // In camera frame, the world origin should have positive z
      // T * [0,0,0,1]^T = [t_x, t_y, t_z, 1]^T
      // So t_z > 0 means origin is in front of camera
      twist[3] = translation_dist(rng);  // translation x (small perturbation)
      twist[4] = translation_dist(rng);  // translation y (small perturbation)
      twist[5] =
          10.0f + translation_dist(rng);  // translation z (origin ~10 in front)
    }

    // Convert twists to SE3 transforms using exponential map
    CudaStream stream;
    constexpr size_t twist_stride = 6;
    constexpr size_t transform_pitch = 4;
    constexpr size_t transform_stride = 16;

    dvector<Vector<6>> twists_device(twists);
    dvector<SE3Transform> poses_device(num_poses);

    auto twists_ptr = reinterpret_cast<const float*>(twists_device.data());
    auto poses_ptr = reinterpret_cast<float*>(poses_device.data());

    ComputeExpSE3(stream.GetStream(), twists_ptr, twist_stride, transform_pitch,
                  transform_stride, num_poses, poses_ptr);
    THROW_ON_CUDA_ERROR(cudaStreamSynchronize(stream.GetStream()));

    poses.resize(num_poses);
    poses_device.CopyToHost(poses.data(), num_poses);
  }

  /**
   * @brief Generates random 3D points visible from all cameras.
   *
   * Creates random points centered around the origin, ensuring they have
   * positive depth when viewed from all camera poses.
   *
   * @param num_points Number of points to generate
   * @param rng Random number generator
   * @param point_dist Distribution for point coordinates
   * @param points Output vector of 3D points
   */
  void GenerateRandomPointsVisibleFromAllCameras(
      size_t num_points, std::mt19937& rng,
      std::uniform_real_distribution<float>& point_dist,
      std::vector<Point3D>& points) {
    points.resize(num_points);
    for (size_t i = 0; i < num_points; i++) {
      // Points centered around origin with small spread
      // Since cameras are ~10 units away looking at origin,
      // points near origin will have depth ~10 in all cameras
      points[i][0] = point_dist(rng);  // x
      points[i][1] = point_dist(rng);  // y
      points[i][2] = point_dist(rng);  // z (can be negative, still in front)
    }
  }

  /**
   * @brief Projects a 3D point through a camera pose to get normalized
   * coordinates.
   *
   * Computes the projection: P_cam = T * P_world, then normalizes by depth.
   * Returns (x/z, y/z) in normalized image coordinates.
   *
   * @note Observations are in NORMALIZED coordinates - no camera intrinsics
   *       (focal length, principal point) are applied. The user must apply
   *       K^-1 to pixel coordinates before using this factor.
   *
   * @param pose SE3 camera pose (world-to-camera transform)
   * @param point 3D point in world coordinates
   * @return 2D observation in normalized coordinates
   */
  Observation2D ProjectPoint(const SE3Transform& pose, const Point3D& point) {
    // Transform point to camera frame: P_cam = R * P_world + t
    float point_cam[3];
    point_cam[0] = pose[0 * 4 + 3];  // tx
    point_cam[1] = pose[1 * 4 + 3];  // ty
    point_cam[2] = pose[2 * 4 + 3];  // tz

    for (int i = 0; i < 3; i++) {
      for (int j = 0; j < 3; j++) {
        point_cam[i] += pose[i * 4 + j] * point[j];
      }
    }

    // Project to normalized coordinates (no intrinsics)
    Observation2D obs;
    float inv_z = 1.0f / point_cam[2];
    obs[0] = point_cam[0] * inv_z;  // x / z
    obs[1] = point_cam[1] * inv_z;  // y / z

    return obs;
  }

  /**
   * @brief Generates observations by projecting all points through all poses.
   *
   * For each (pose, point) pair, computes the normalized 2D observation.
   * The observations are stored in a flat array with the layout:
   *   observations_[pose_idx * num_points + point_idx]
   *
   * This creates a total of (num_poses * num_points) observations.
   */
  void GenerateObservations() {
    size_t num_observations = num_poses_ * num_points_;
    observations_.resize(num_observations);

    for (size_t pose_idx = 0; pose_idx < num_poses_; pose_idx++) {
      for (size_t point_idx = 0; point_idx < num_points_; point_idx++) {
        size_t obs_idx = pose_idx * num_points_ + point_idx;
        observations_[obs_idx] = ProjectPoint(ground_truth_poses_[pose_idx],
                                              ground_truth_points_[point_idx]);
      }
    }
  }

  /**
   * @brief Disturbs 3D points by adding random noise.
   *
   * Ensures that disturbed points remain visible from all cameras
   * (positive depth > kMinDepth in all camera frames).
   *
   * @param points Points to disturb (modified in place)
   * @param noise_magnitude Maximum noise magnitude per coordinate
   */
  void DisturbPoints(std::vector<Point3D>& points, float noise_magnitude) {
    std::mt19937 rng(fixed_seed_ + 1);  // Different seed for disturbance
    std::uniform_real_distribution<float> noise_dist(-noise_magnitude,
                                                     noise_magnitude);
    for (auto& point : points) {
      Point3D disturbed;
      bool valid = false;

      // Retry until we get a valid disturbance that keeps point visible
      for (int attempt = 0; attempt < 100 && !valid; attempt++) {
        disturbed[0] = point[0] + noise_dist(rng);
        disturbed[1] = point[1] + noise_dist(rng);
        disturbed[2] = point[2] + noise_dist(rng);

        // Check visibility from all cameras
        valid = true;
        for (const auto& pose : ground_truth_poses_) {
          if (ComputePointDepth(pose, disturbed) < kMinDepth) {
            valid = false;
            break;
          }
        }
      }

      if (valid) {
        point = disturbed;
      }
      // If no valid disturbance found after 100 attempts, keep original point
    }
  }

  /**
   * @brief Disturbs camera poses by applying random perturbations in tangent
   * space.
   *
   * @param poses Poses to disturb (modified in place)
   * @param rotation_noise Maximum rotation noise (radians)
   * @param translation_noise Maximum translation noise
   */
  void DisturbPoses(std::vector<SE3Transform>& poses, float rotation_noise,
                    float translation_noise) {
    std::mt19937 rng(fixed_seed_ + 2);  // Different seed for disturbance
    std::uniform_real_distribution<float> rot_dist(-rotation_noise,
                                                   rotation_noise);
    std::uniform_real_distribution<float> trans_dist(-translation_noise,
                                                     translation_noise);

    // Generate perturbation twists
    hvector<Vector<6>> deltas(poses.size());
    for (size_t i = 0; i < poses.size(); i++) {
      deltas[i][0] = rot_dist(rng);
      deltas[i][1] = rot_dist(rng);
      deltas[i][2] = rot_dist(rng);
      deltas[i][3] = trans_dist(rng);
      deltas[i][4] = trans_dist(rng);
      deltas[i][5] = trans_dist(rng);
    }

    // Apply perturbations using SE3 exponential map
    CudaStream stream;
    constexpr size_t twist_stride = 6;
    constexpr size_t transform_pitch = 4;
    constexpr size_t transform_stride = 16;

    dvector<Vector<6>> deltas_device(deltas);
    dvector<SE3Transform> poses_device(poses);
    dvector<SE3Transform> exp_deltas_device(poses.size());

    // Compute exp(delta)
    auto deltas_ptr = reinterpret_cast<const float*>(deltas_device.data());
    auto exp_deltas_ptr = reinterpret_cast<float*>(exp_deltas_device.data());
    ComputeExpSE3(stream.GetStream(), deltas_ptr, twist_stride, transform_pitch,
                  transform_stride, poses.size(), exp_deltas_ptr);

    // Multiply: pose_disturbed = exp(delta) * pose
    cuBLASHandle cublas_handle;
    auto handle = cublas_handle.GetHandle(stream.GetStream());
    constexpr float alpha = 1.0f;
    constexpr float beta = 0.0f;
    constexpr size_t mat_size = 4;

    auto poses_ptr = reinterpret_cast<float*>(poses_device.data());
    THROW_ON_CUBLAS_ERROR(cublasSgemmStridedBatched(
        handle, CUBLAS_OP_N, CUBLAS_OP_N, mat_size, mat_size, mat_size, &alpha,
        poses_ptr, mat_size, transform_stride, exp_deltas_ptr, mat_size,
        transform_stride, &beta, poses_ptr, mat_size, transform_stride,
        poses.size()));

    THROW_ON_CUDA_ERROR(cudaStreamSynchronize(stream.GetStream()));
    poses_device.CopyToHost(poses.data(), poses.size());
  }

  /**
   * @brief Creates state pointers for all observations.
   *
   * Builds the state pointer array where each observation has:
   *   [pose_ptr, point_ptr]
   *
   * @param state_batch_poses SE3 state batch for poses
   * @param state_batch_points Vector state batch for points
   * @return Vector of state pointers for all observations
   */
  std::vector<float*> CreateStatePointers(
      SE3StateBatch& state_batch_poses,
      VectorStateBatch<3>& state_batch_points) {
    std::vector<float*> state_pointers;
    state_pointers.reserve(2 * num_poses_ * num_points_);

    for (size_t pose_idx = 0; pose_idx < num_poses_; pose_idx++) {
      for (size_t point_idx = 0; point_idx < num_points_; point_idx++) {
        state_pointers.push_back(
            state_batch_poses.StateBlockDevicePtr(pose_idx));
        state_pointers.push_back(
            state_batch_points.StateBlockDevicePtr(point_idx));
      }
    }

    return state_pointers;
  }

  /**
   * @brief Computes the mean squared error between two sets of 3D points.
   *
   * @param points_a First set of points
   * @param points_b Second set of points
   * @return Mean squared Euclidean distance
   */
  float ComputePointMSE(const std::vector<Point3D>& points_a,
                        const std::vector<Point3D>& points_b) {
    assert(points_a.size() == points_b.size());
    float mse = 0.0f;
    for (size_t i = 0; i < points_a.size(); i++) {
      float dx = points_a[i][0] - points_b[i][0];
      float dy = points_a[i][1] - points_b[i][1];
      float dz = points_a[i][2] - points_b[i][2];
      mse += dx * dx + dy * dy + dz * dz;
    }
    return mse / static_cast<float>(points_a.size());
  }

  /**
   * @brief Computes the mean Frobenius norm error between two sets of SE3
   * transforms.
   *
   * @param poses_a First set of poses
   * @param poses_b Second set of poses
   * @return Mean squared Frobenius norm of differences
   */
  float ComputePoseMSE(const std::vector<SE3Transform>& poses_a,
                       const std::vector<SE3Transform>& poses_b) {
    assert(poses_a.size() == poses_b.size());
    float mse = 0.0f;
    for (size_t i = 0; i < poses_a.size(); i++) {
      float frobenius_sq = 0.0f;
      for (int j = 0; j < 16; j++) {
        float diff = poses_a[i][j] - poses_b[i][j];
        frobenius_sq += diff * diff;
      }
      mse += frobenius_sq;
    }
    return mse / static_cast<float>(poses_a.size());
  }

  // Test configuration
  const size_t num_poses_ = 10;        ///< Number of camera poses
  const size_t num_points_ = 5000;     ///< Number of 3D points
  const uint32_t fixed_seed_ = 12345;  ///< Random seed for reproducibility

  // Ground truth data
  std::vector<SE3Transform> ground_truth_poses_;  ///< Ground truth camera poses
  std::vector<Point3D> ground_truth_points_;      ///< Ground truth 3D points
  std::vector<Observation2D> observations_;  ///< 2D observations (normalized)

  cuBLASHandle cublas_handle_;  ///< cuBLAS handle for factor constructors

  profiler::Domain profiler_domain_{"ReprojectionFactorBatchTest"};
};

/**
 * @brief Tests basic evaluation of reprojection factor.
 *
 * Verifies that the Evaluate method executes without errors and produces
 * correct residuals when states match the observations (zero residual).
 */
TEST_F(ReprojectionFactorBatchTest, EvaluateBasic) {
  auto test_range = profiler_domain_.CreateDomainRange("EvaluateBasic");

  // Copy data to device
  dvector<SE3Transform> poses_device(ground_truth_poses_);
  dvector<Point3D> points_device(ground_truth_points_);
  dvector<Observation2D> observations_device(observations_);

  // Create factor batch with explicit z_threshold
  size_t num_observations = num_poses_ * num_points_;
  ReprojectionFactorBatch factor_batch(
      cublas_handle_, observations_device.data(), num_observations, kDefaultZThreshold);

  // Set up state pointers
  std::vector<const float*> state_pointers;
  for (size_t pose_idx = 0; pose_idx < num_poses_; pose_idx++) {
    for (size_t point_idx = 0; point_idx < num_points_; point_idx++) {
      state_pointers.push_back(
          reinterpret_cast<const float*>(poses_device.data() + pose_idx));
      state_pointers.push_back(
          reinterpret_cast<const float*>(points_device.data() + point_idx));
    }
  }
  dvector<const float*> state_pointers_device(state_pointers);

  // Allocate residuals and jacobians
  dvector<float> residuals(num_observations * 2);
  dvector<float> jacobians(num_observations * 2 * 9);  // 2 rows, 9 cols per obs

  CudaStream stream;
  factor_batch.Evaluate(residuals.data(), jacobians.data(),
                         state_pointers_device.data(), stream.GetStream());
  THROW_ON_CUDA_ERROR(cudaStreamSynchronize(stream.GetStream()));

  // Verify residuals are near zero (ground truth should project exactly)
  std::vector<float> host_residuals(num_observations * 2);
  residuals.CopyToHost(host_residuals.data(), host_residuals.size());

  float max_residual = 0.0f;
  for (float r : host_residuals) {
    max_residual = std::max(max_residual, std::abs(r));
  }
  EXPECT_LT(max_residual, 1e-5f)
      << "Residuals should be near zero for ground truth";
}

/**
 * @brief Tests optimization to recover disturbed 3D points.
 *
 * Starting from ground truth poses and disturbed points, verifies that
 * optimization recovers the original point positions.
 *
 * Setup:
 * - Poses: Fixed at ground truth values
 * - Points: Disturbed from ground truth
 * - Observations: Generated from ground truth (normalized coordinates)
 *
 * Expected: After optimization, points should converge to ground truth.
 */
TEST_F(ReprojectionFactorBatchTest, OptimizeDisturbedPoints) {
  auto test_range =
      profiler_domain_.CreateDomainRange("OptimizeDisturbedPoints");

  // Create disturbed copy of points
  std::vector<Point3D> disturbed_points = ground_truth_points_;
  DisturbPoints(disturbed_points, 0.5f);  // Add noise up to 0.5 units

  // Verify points are actually disturbed
  float initial_mse = ComputePointMSE(disturbed_points, ground_truth_points_);
  ASSERT_GT(initial_mse, 0.01f) << "Points should be significantly disturbed";

  // Copy data to device
  dvector<SE3Transform> poses_device(ground_truth_poses_);
  dvector<Point3D> points_device(disturbed_points);
  dvector<Observation2D> observations_device(observations_);

  // Create constant state IDs for poses (all poses are fixed)
  std::vector<int> const_pose_ids(num_poses_);
  for (size_t i = 0; i < num_poses_; i++) {
    const_pose_ids[i] = static_cast<int>(i);
  }
  dvector<int> const_pose_ids_device(const_pose_ids);

  // Create state batches
  const float* poses_ptr = reinterpret_cast<const float*>(poses_device.data());
  const float* points_ptr =
      reinterpret_cast<const float*>(points_device.data());

  SE3StateBatch state_batch_poses(
      cublas_handle_, poses_ptr, num_poses_, const_pose_ids_device.data(), num_poses_);
  VectorStateBatch<3> state_batch_points(points_ptr, num_points_);

  // Create factor batch with explicit z_threshold
  size_t num_observations = num_poses_ * num_points_;
  ReprojectionFactorBatch factor_batch(
      cublas_handle_, observations_device.data(), num_observations, kDefaultZThreshold);

  // Create state pointers and build problem
  std::vector<float*> state_pointers =
      CreateStatePointers(state_batch_poses, state_batch_points);

  Problem problem;
  problem.AddStateBatch(&state_batch_poses);
  problem.AddStateBatch(&state_batch_points);
  problem.AddFactorBatch(&factor_batch, state_pointers);

  ASSERT_TRUE(problem.CheckConsistency());

  // Optimize using Levenberg-Marquardt
  CudaStream stream;
  MinimizerOptions options;
  options.max_num_iterations = 100;
  options.state_tolerance = 1e-8f;
  options.cost_tolerance = 1e-8f;

  LevenbergMarquardtMinimizerOptions lm_options;
  lm_options.base_options = options;
  lm_options.initial_lambda = 1e-3f;
  LevenbergMarquardtMinimizer minimizer(lm_options);

  MinimizerSummary summary;
  {
    auto minimize_range = profiler_domain_.CreateDomainRange("Minimize");
    summary = minimizer.Minimize(stream.GetStream(), problem);
    THROW_ON_CUDA_ERROR(cudaStreamSynchronize(stream.GetStream()));
  }

  // Verify optimization converged
  EXPECT_LT(summary.final_cost, 1e-4f) << "Optimization should converge";
  EXPECT_GT(summary.num_iterations, 0) << "Should take at least one iteration";

  // Copy optimized points back to host
  std::vector<Point3D> optimized_points(num_points_);
  points_device.CopyToHost(optimized_points.data(), num_points_);

  // Verify points recovered to ground truth
  float final_mse = ComputePointMSE(optimized_points, ground_truth_points_);
  EXPECT_LT(final_mse, 1e-4f) << "Points should converge to ground truth";
  EXPECT_LT(final_mse, initial_mse * 0.01f)
      << "Final MSE should be much smaller than initial";
}

/**
 * @brief Tests optimization to recover disturbed camera poses.
 *
 * Starting from disturbed poses and ground truth points, verifies that
 * optimization recovers the original pose values.
 *
 * Setup:
 * - Poses: Disturbed from ground truth
 * - Points: Fixed at ground truth values
 * - Observations: Generated from ground truth (normalized coordinates)
 *
 * Expected: After optimization, poses should converge to ground truth.
 */
TEST_F(ReprojectionFactorBatchTest, OptimizeDisturbedPoses) {
  auto test_range =
      profiler_domain_.CreateDomainRange("OptimizeDisturbedPoses");

  // Create disturbed copy of poses
  std::vector<SE3Transform> disturbed_poses = ground_truth_poses_;
  DisturbPoses(disturbed_poses, 0.05f,
               0.2f);  // Small rotation, moderate translation noise

  // Verify poses are actually disturbed
  float initial_mse = ComputePoseMSE(disturbed_poses, ground_truth_poses_);
  ASSERT_GT(initial_mse, 0.001f) << "Poses should be significantly disturbed";

  // Copy data to device
  dvector<SE3Transform> poses_device(disturbed_poses);
  dvector<Point3D> points_device(ground_truth_points_);
  dvector<Observation2D> observations_device(observations_);

  // Create constant state IDs for points (all points are fixed)
  std::vector<int> const_point_ids(num_points_);
  for (size_t i = 0; i < num_points_; i++) {
    const_point_ids[i] = static_cast<int>(i);
  }
  dvector<int> const_point_ids_device(const_point_ids);

  // Create state batches
  const float* poses_ptr = reinterpret_cast<const float*>(poses_device.data());
  const float* points_ptr =
      reinterpret_cast<const float*>(points_device.data());

  SE3StateBatch state_batch_poses(cublas_handle_, poses_ptr, num_poses_);
  VectorStateBatch<3> state_batch_points(
      points_ptr, num_points_, const_point_ids_device.data(), num_points_);

  // Create factor batch with explicit z_threshold
  size_t num_observations = num_poses_ * num_points_;
  ReprojectionFactorBatch factor_batch(
      cublas_handle_, observations_device.data(), num_observations, kDefaultZThreshold);

  // Create state pointers and build problem
  std::vector<float*> state_pointers =
      CreateStatePointers(state_batch_poses, state_batch_points);

  Problem problem;
  problem.AddStateBatch(&state_batch_poses);
  problem.AddStateBatch(&state_batch_points);
  problem.AddFactorBatch(&factor_batch, state_pointers);

  ASSERT_TRUE(problem.CheckConsistency());

  // Optimize using Levenberg-Marquardt
  CudaStream stream;
  MinimizerOptions options;
  options.max_num_iterations = 100;
  options.state_tolerance = 1e-8f;
  options.cost_tolerance = 1e-8f;

  LevenbergMarquardtMinimizerOptions lm_options;
  lm_options.base_options = options;
  lm_options.initial_lambda = 1e-3f;
  LevenbergMarquardtMinimizer minimizer(lm_options);

  MinimizerSummary summary;
  {
    auto minimize_range = profiler_domain_.CreateDomainRange("Minimize");
    summary = minimizer.Minimize(stream.GetStream(), problem);
    THROW_ON_CUDA_ERROR(cudaStreamSynchronize(stream.GetStream()));
  }

  // Verify optimization converged
  EXPECT_LT(summary.final_cost, 1e-4f) << "Optimization should converge";
  EXPECT_GT(summary.num_iterations, 0) << "Should take at least one iteration";

  // Copy optimized poses back to host
  std::vector<SE3Transform> optimized_poses(num_poses_);
  poses_device.CopyToHost(optimized_poses.data(), num_poses_);

  // Verify poses recovered to ground truth
  float final_mse = ComputePoseMSE(optimized_poses, ground_truth_poses_);
  EXPECT_LT(final_mse, 1e-3f) << "Poses should converge to ground truth";
  EXPECT_LT(final_mse, initial_mse * 0.1f)
      << "Final MSE should be much smaller than initial";
}

/**
 * @brief Tests joint optimization of both poses and points.
 *
 * Starting from slightly disturbed poses and points, verifies that
 * joint optimization reduces the reprojection error.
 *
 * Note: This is an underconstrained problem (gauge freedom), so we
 * only verify cost reduction, not exact recovery of ground truth.
 */
TEST_F(ReprojectionFactorBatchTest, OptimizeJoint) {
  auto test_range = profiler_domain_.CreateDomainRange("OptimizeJoint");

  // Create disturbed copies
  std::vector<SE3Transform> disturbed_poses = ground_truth_poses_;
  std::vector<Point3D> disturbed_points = ground_truth_points_;
  DisturbPoses(disturbed_poses, 0.02f, 0.1f);  // Small disturbance
  DisturbPoints(disturbed_points, 0.2f);

  // Copy data to device
  dvector<SE3Transform> poses_device(disturbed_poses);
  dvector<Point3D> points_device(disturbed_points);
  dvector<Observation2D> observations_device(observations_);

  // Create state batches (no constant states)
  const float* poses_ptr = reinterpret_cast<const float*>(poses_device.data());
  const float* points_ptr =
      reinterpret_cast<const float*>(points_device.data());

  SE3StateBatch state_batch_poses(cublas_handle_, poses_ptr, num_poses_);
  VectorStateBatch<3> state_batch_points(points_ptr, num_points_);

  // Create factor batch with explicit z_threshold
  size_t num_observations = num_poses_ * num_points_;
  ReprojectionFactorBatch factor_batch(
      cublas_handle_, observations_device.data(), num_observations, kDefaultZThreshold);

  // Create state pointers and build problem
  std::vector<float*> state_pointers =
      CreateStatePointers(state_batch_poses, state_batch_points);

  Problem problem;
  problem.AddStateBatch(&state_batch_points);
  problem.AddStateBatch(&state_batch_poses);
  problem.AddFactorBatch(&factor_batch, state_pointers);

  ASSERT_TRUE(problem.CheckConsistency());

  // Optimize using Levenberg-Marquardt
  CudaStream stream;
  MinimizerOptions options;
  options.max_num_iterations = 200;
  options.state_tolerance = 1e-8f;
  options.cost_tolerance = 1e-10f;

  LevenbergMarquardtMinimizerOptions lm_options;
  lm_options.base_options = options;
  lm_options.initial_lambda = 1e-4f;
  LevenbergMarquardtMinimizer minimizer(lm_options);

  MinimizerSummary summary;
  {
    auto minimize_range = profiler_domain_.CreateDomainRange("Minimize");
    summary = minimizer.Minimize(stream.GetStream(), problem);
    THROW_ON_CUDA_ERROR(cudaStreamSynchronize(stream.GetStream()));
  }

  // Verify optimization reduced cost significantly
  EXPECT_LT(summary.final_cost, summary.initial_cost * 0.01f)
      << "Cost should be significantly reduced";
  EXPECT_LT(summary.final_cost, 1e-3f) << "Final cost should be very small";
}

/**
 * @brief Tests that the factor correctly handles points behind the
 * camera.
 *
 * Verifies that points with depth below z_threshold produce zero residuals
 * and zero Jacobians to avoid numerical instability.
 */
TEST_F(ReprojectionFactorBatchTest, ZThresholdHandling) {
  auto test_range = profiler_domain_.CreateDomainRange("ZThresholdHandling");

  // Create a simple test case with one pose and one point
  // Position the point behind the camera (negative z in camera frame)
  SE3Transform identity_pose;
  identity_pose.fill(0.0f);
  identity_pose[0] = 1.0f;   // R(0,0)
  identity_pose[5] = 1.0f;   // R(1,1)
  identity_pose[10] = 1.0f;  // R(2,2)
  identity_pose[15] = 1.0f;  // homogeneous

  Point3D point_behind;
  point_behind[0] = 1.0f;
  point_behind[1] = 1.0f;
  point_behind[2] = -1.0f;  // Behind camera (negative z)

  Observation2D dummy_obs;
  dummy_obs[0] = 0.0f;
  dummy_obs[1] = 0.0f;

  // Copy to device
  dvector<SE3Transform> pose_device({identity_pose});
  dvector<Point3D> point_device({point_behind});
  dvector<Observation2D> obs_device({dummy_obs});

  // Create factor batch with explicit positive z_threshold to test the check
  constexpr float z_threshold_for_test = 1e-3f;
  ReprojectionFactorBatch factor_batch(cublas_handle_, obs_device.data(), 1,
                                              z_threshold_for_test);

  // Set up state pointers
  std::vector<const float*> param_ptrs = {
      reinterpret_cast<const float*>(pose_device.data()),
      reinterpret_cast<const float*>(point_device.data())};
  dvector<const float*> param_ptrs_device(param_ptrs);

  // Allocate outputs
  dvector<float> residuals(2);
  dvector<float> jacobians(2 * 9);

  CudaStream stream;
  factor_batch.Evaluate(residuals.data(), jacobians.data(),
                         param_ptrs_device.data(), stream.GetStream());
  THROW_ON_CUDA_ERROR(cudaStreamSynchronize(stream.GetStream()));

  // Verify residuals are zero (point behind camera)
  std::vector<float> host_residuals(2);
  residuals.CopyToHost(host_residuals.data(), 2);

  EXPECT_FLOAT_EQ(host_residuals[0], 0.0f) << "Residual x should be zero";
  EXPECT_FLOAT_EQ(host_residuals[1], 0.0f) << "Residual y should be zero";

  // Verify Jacobians are zero
  std::vector<float> host_jacobians(2 * 9);
  jacobians.CopyToHost(host_jacobians.data(), 2 * 9);

  for (int i = 0; i < 2 * 9; i++) {
    EXPECT_FLOAT_EQ(host_jacobians[i], 0.0f)
        << "Jacobian element " << i << " should be zero";
  }
}

/**
 * @brief Tests evaluation with identity camera-from-rig transforms.
 *
 * Verifies that when poses_camera_from_rig is the identity matrix,
 * the results are identical to not providing the rig transforms at all.
 */
TEST_F(ReprojectionFactorBatchTest, EvaluateWithIdentityRigTransform) {
  auto test_range =
      profiler_domain_.CreateDomainRange("EvaluateWithIdentityRigTransform");

  // Copy data to device
  dvector<SE3Transform> poses_device(ground_truth_poses_);
  dvector<Point3D> points_device(ground_truth_points_);
  dvector<Observation2D> observations_device(observations_);

  // Create identity camera-from-rig transforms for each observation
  size_t num_observations = num_poses_ * num_points_;
  SE3Transform identity;
  identity.fill(0.0f);
  identity[0] = 1.0f;   // R(0,0)
  identity[5] = 1.0f;   // R(1,1)
  identity[10] = 1.0f;  // R(2,2)
  identity[15] = 1.0f;  // homogeneous

  std::vector<SE3Transform> identity_rig_transforms(num_observations, identity);
  dvector<SE3Transform> rig_transforms_device(identity_rig_transforms);

  // Create factor batch with rig transforms
  ReprojectionFactorBatch factor_batch_with_rig(
      cublas_handle_, observations_device.data(), rig_transforms_device.data(),
      num_observations, kDefaultZThreshold);

  // Create factor batch without rig transforms for comparison
  ReprojectionFactorBatch factor_batch_no_rig(
      cublas_handle_, observations_device.data(), num_observations, kDefaultZThreshold);

  // Set up state pointers
  std::vector<const float*> state_pointers;
  for (size_t pose_idx = 0; pose_idx < num_poses_; pose_idx++) {
    for (size_t point_idx = 0; point_idx < num_points_; point_idx++) {
      state_pointers.push_back(
          reinterpret_cast<const float*>(poses_device.data() + pose_idx));
      state_pointers.push_back(
          reinterpret_cast<const float*>(points_device.data() + point_idx));
    }
  }
  dvector<const float*> state_pointers_device(state_pointers);

  // Allocate residuals for both factor batches
  dvector<float> residuals_with_rig(num_observations * 2);
  dvector<float> residuals_no_rig(num_observations * 2);
  dvector<float> jacobians_with_rig(num_observations * 2 * 9);
  dvector<float> jacobians_no_rig(num_observations * 2 * 9);

  CudaStream stream;

  // Evaluate both factor batches
  factor_batch_with_rig.Evaluate(
      residuals_with_rig.data(), jacobians_with_rig.data(),
      state_pointers_device.data(), stream.GetStream());

  factor_batch_no_rig.Evaluate(
      residuals_no_rig.data(), jacobians_no_rig.data(),
      state_pointers_device.data(), stream.GetStream());

  THROW_ON_CUDA_ERROR(cudaStreamSynchronize(stream.GetStream()));

  // Copy results to host and compare
  std::vector<float> host_residuals_with_rig(num_observations * 2);
  std::vector<float> host_residuals_no_rig(num_observations * 2);
  residuals_with_rig.CopyToHost(host_residuals_with_rig.data(),
                                host_residuals_with_rig.size());
  residuals_no_rig.CopyToHost(host_residuals_no_rig.data(),
                              host_residuals_no_rig.size());

  // Verify residuals match
  for (size_t i = 0; i < num_observations * 2; i++) {
    EXPECT_NEAR(host_residuals_with_rig[i], host_residuals_no_rig[i], 1e-5f)
        << "Residual mismatch at index " << i;
  }

  // Copy and compare Jacobians
  std::vector<float> host_jacobians_with_rig(num_observations * 2 * 9);
  std::vector<float> host_jacobians_no_rig(num_observations * 2 * 9);
  jacobians_with_rig.CopyToHost(host_jacobians_with_rig.data(),
                                host_jacobians_with_rig.size());
  jacobians_no_rig.CopyToHost(host_jacobians_no_rig.data(),
                              host_jacobians_no_rig.size());

  for (size_t i = 0; i < num_observations * 2 * 9; i++) {
    EXPECT_NEAR(host_jacobians_with_rig[i], host_jacobians_no_rig[i], 1e-5f)
        << "Jacobian mismatch at index " << i;
  }
}

/**
 * @brief Tests optimization with camera-from-rig transforms.
 *
 * Creates a multi-camera rig scenario where each observation has a different
 * camera offset from the rig. The rig poses are optimized while the camera-
 * from-rig transforms are fixed.
 *
 * Setup:
 * - Rig poses: Disturbed from ground truth (to be optimized)
 * - Camera-from-rig: Fixed transforms representing camera mounting offsets
 * - Points: Fixed at ground truth values
 * - Observations: Generated using T_cam_world = T_cam_rig * T_rig_world
 *
 * Expected: After optimization, rig poses should converge such that
 * reprojection error is minimized.
 */
TEST_F(ReprojectionFactorBatchTest, OptimizeRigPosesWithCameraOffsets) {
  auto test_range =
      profiler_domain_.CreateDomainRange("OptimizeRigPosesWithCameraOffsets");

  // Create camera-from-rig transforms (different offset per pose index)
  // This simulates a multi-camera rig where cameras have fixed mounting offsets
  size_t num_observations = num_poses_ * num_points_;
  std::vector<SE3Transform> camera_from_rig_transforms(num_observations);

  // Generate small random camera offsets for each pose
  std::mt19937 rng(fixed_seed_ + 100);
  std::uniform_real_distribution<float> offset_dist(-0.1f, 0.1f);

  for (size_t pose_idx = 0; pose_idx < num_poses_; pose_idx++) {
    // Create a small rotation and translation offset for this camera
    SE3Transform offset;
    offset.fill(0.0f);

    // Small rotation (approximate identity with small perturbation)
    float rx = offset_dist(rng) * 0.1f;  // Small rotation angles
    float ry = offset_dist(rng) * 0.1f;
    float rz = offset_dist(rng) * 0.1f;

    // Approximate rotation matrix for small angles (R ≈ I + [w]_x)
    offset[0] = 1.0f;
    offset[1] = -rz;
    offset[2] = ry;
    offset[4] = rz;
    offset[5] = 1.0f;
    offset[6] = -rx;
    offset[8] = -ry;
    offset[9] = rx;
    offset[10] = 1.0f;

    // Small translation offset
    offset[3] = offset_dist(rng) * 0.05f;   // tx
    offset[7] = offset_dist(rng) * 0.05f;   // ty
    offset[11] = offset_dist(rng) * 0.05f;  // tz
    offset[15] = 1.0f;

    // Apply same camera offset for all points observed by this pose
    for (size_t point_idx = 0; point_idx < num_points_; point_idx++) {
      size_t obs_idx = pose_idx * num_points_ + point_idx;
      camera_from_rig_transforms[obs_idx] = offset;
    }
  }

  // Compute camera poses from rig poses for generating ground truth
  // observations T_cam_world = T_cam_rig * T_rig_world
  std::vector<SE3Transform> camera_from_world_poses(num_observations);
  for (size_t pose_idx = 0; pose_idx < num_poses_; pose_idx++) {
    const SE3Transform& T_rig_world = ground_truth_poses_[pose_idx];
    for (size_t point_idx = 0; point_idx < num_points_; point_idx++) {
      size_t obs_idx = pose_idx * num_points_ + point_idx;
      const SE3Transform& T_cam_rig = camera_from_rig_transforms[obs_idx];

      // Matrix multiplication: T_cam_world = T_cam_rig * T_rig_world
      SE3Transform& T_cam_world = camera_from_world_poses[obs_idx];
      T_cam_world.fill(0.0f);
      for (int i = 0; i < 4; i++) {
        for (int j = 0; j < 4; j++) {
          for (int k = 0; k < 4; k++) {
            T_cam_world[i * 4 + j] +=
                T_cam_rig[i * 4 + k] * T_rig_world[k * 4 + j];
          }
        }
      }
    }
  }

  // Generate observations using the composed camera poses
  std::vector<Observation2D> observations_with_rig(num_observations);
  for (size_t pose_idx = 0; pose_idx < num_poses_; pose_idx++) {
    for (size_t point_idx = 0; point_idx < num_points_; point_idx++) {
      size_t obs_idx = pose_idx * num_points_ + point_idx;
      observations_with_rig[obs_idx] = ProjectPoint(
          camera_from_world_poses[obs_idx], ground_truth_points_[point_idx]);
    }
  }

  // Create disturbed rig poses for optimization
  std::vector<SE3Transform> disturbed_rig_poses = ground_truth_poses_;
  DisturbPoses(disturbed_rig_poses, 0.03f, 0.15f);

  // Verify poses are disturbed
  float initial_mse = ComputePoseMSE(disturbed_rig_poses, ground_truth_poses_);
  ASSERT_GT(initial_mse, 0.001f) << "Rig poses should be disturbed";

  // Copy data to device
  dvector<SE3Transform> rig_poses_device(disturbed_rig_poses);
  dvector<Point3D> points_device(ground_truth_points_);
  dvector<Observation2D> observations_device(observations_with_rig);
  dvector<SE3Transform> camera_from_rig_device(camera_from_rig_transforms);

  // Create constant state IDs for points (all points are fixed)
  std::vector<int> const_point_ids(num_points_);
  for (size_t i = 0; i < num_points_; i++) {
    const_point_ids[i] = static_cast<int>(i);
  }
  dvector<int> const_point_ids_device(const_point_ids);

  // Create state batches
  const float* poses_ptr =
      reinterpret_cast<const float*>(rig_poses_device.data());
  const float* points_ptr =
      reinterpret_cast<const float*>(points_device.data());

  SE3StateBatch state_batch_poses(cublas_handle_, poses_ptr, num_poses_);
  VectorStateBatch<3> state_batch_points(
      points_ptr, num_points_, const_point_ids_device.data(), num_points_);

  // Create factor batch with camera-from-rig transforms
  ReprojectionFactorBatch factor_batch(
      cublas_handle_, observations_device.data(), camera_from_rig_device.data(),
      num_observations, kDefaultZThreshold);

  // Create state pointers and build problem
  std::vector<float*> state_pointers =
      CreateStatePointers(state_batch_poses, state_batch_points);

  Problem problem;
  problem.AddStateBatch(&state_batch_poses);
  problem.AddStateBatch(&state_batch_points);
  problem.AddFactorBatch(&factor_batch, state_pointers);

  ASSERT_TRUE(problem.CheckConsistency());

  // Optimize using Levenberg-Marquardt
  CudaStream stream;
  MinimizerOptions options;
  options.max_num_iterations = 100;
  options.state_tolerance = 1e-8f;
  options.cost_tolerance = 1e-8f;

  LevenbergMarquardtMinimizerOptions lm_options;
  lm_options.base_options = options;
  lm_options.initial_lambda = 1e-3f;
  LevenbergMarquardtMinimizer minimizer(lm_options);

  MinimizerSummary summary;
  {
    auto minimize_range = profiler_domain_.CreateDomainRange("Minimize");
    summary = minimizer.Minimize(stream.GetStream(), problem);
    THROW_ON_CUDA_ERROR(cudaStreamSynchronize(stream.GetStream()));
  }

  // Verify optimization converged
  EXPECT_LT(summary.final_cost, 1e-4f) << "Optimization should converge";
  EXPECT_GT(summary.num_iterations, 0) << "Should take at least one iteration";

  // Copy optimized rig poses back to host
  std::vector<SE3Transform> optimized_rig_poses(num_poses_);
  rig_poses_device.CopyToHost(optimized_rig_poses.data(), num_poses_);

  // Verify rig poses recovered to ground truth
  float final_mse = ComputePoseMSE(optimized_rig_poses, ground_truth_poses_);
  EXPECT_LT(final_mse, 1e-3f) << "Rig poses should converge to ground truth";
  EXPECT_LT(final_mse, initial_mse * 0.1f)
      << "Final MSE should be much smaller than initial";
}

/**
 * @brief Tests that camera-from-rig transform correctly composes with rig pose.
 *
 * Verifies that providing T_cam_rig and optimizing T_rig_world produces
 * the same result as optimizing T_cam_world directly (when T_cam_rig is known).
 */
TEST_F(ReprojectionFactorBatchTest, RigTransformCompositionCorrectness) {
  auto test_range =
      profiler_domain_.CreateDomainRange("RigTransformCompositionCorrectness");

  // Use a single pose and multiple points for this test
  size_t test_num_poses = 1;
  size_t test_num_points = 100;
  size_t num_observations = test_num_poses * test_num_points;

  // Use the first pose and first 100 points from ground truth
  SE3Transform rig_pose = ground_truth_poses_[0];
  std::vector<Point3D> test_points(
      ground_truth_points_.begin(),
      ground_truth_points_.begin() + test_num_points);

  // Create a non-trivial camera-from-rig transform
  SE3Transform camera_from_rig;
  camera_from_rig.fill(0.0f);
  // 45-degree rotation around Z axis
  float cos45 = 0.7071067811865476f;
  float sin45 = 0.7071067811865476f;
  camera_from_rig[0] = cos45;
  camera_from_rig[1] = -sin45;
  camera_from_rig[4] = sin45;
  camera_from_rig[5] = cos45;
  camera_from_rig[10] = 1.0f;
  // Small translation offset
  camera_from_rig[3] = 0.1f;    // tx
  camera_from_rig[7] = -0.05f;  // ty
  camera_from_rig[11] = 0.02f;  // tz
  camera_from_rig[15] = 1.0f;

  // Compute the composed camera pose: T_cam_world = T_cam_rig * T_rig_world
  SE3Transform camera_from_world;
  camera_from_world.fill(0.0f);
  for (int i = 0; i < 4; i++) {
    for (int j = 0; j < 4; j++) {
      for (int k = 0; k < 4; k++) {
        camera_from_world[i * 4 + j] +=
            camera_from_rig[i * 4 + k] * rig_pose[k * 4 + j];
      }
    }
  }

  // Generate observations using the composed camera pose
  std::vector<Observation2D> test_observations(num_observations);
  for (size_t i = 0; i < test_num_points; i++) {
    test_observations[i] = ProjectPoint(camera_from_world, test_points[i]);
  }

  // Copy data to device
  dvector<SE3Transform> rig_pose_device({rig_pose});
  dvector<Point3D> points_device(test_points);
  dvector<Observation2D> observations_device(test_observations);

  // Create camera-from-rig transforms for each observation
  std::vector<SE3Transform> camera_from_rig_vec(num_observations,
                                                camera_from_rig);
  dvector<SE3Transform> camera_from_rig_device(camera_from_rig_vec);

  // Create factor batch with rig transforms
  ReprojectionFactorBatch factor_batch(
      cublas_handle_, observations_device.data(), camera_from_rig_device.data(),
      num_observations, kDefaultZThreshold);

  // Set up state pointers
  std::vector<const float*> state_pointers;
  for (size_t point_idx = 0; point_idx < test_num_points; point_idx++) {
    state_pointers.push_back(
        reinterpret_cast<const float*>(rig_pose_device.data()));
    state_pointers.push_back(
        reinterpret_cast<const float*>(points_device.data() + point_idx));
  }
  dvector<const float*> state_pointers_device(state_pointers);

  // Allocate residuals
  dvector<float> residuals(num_observations * 2);

  CudaStream stream;
  factor_batch.Evaluate(residuals.data(), nullptr,
                         state_pointers_device.data(), stream.GetStream());
  THROW_ON_CUDA_ERROR(cudaStreamSynchronize(stream.GetStream()));

  // Verify residuals are near zero (ground truth should project exactly)
  std::vector<float> host_residuals(num_observations * 2);
  residuals.CopyToHost(host_residuals.data(), host_residuals.size());

  float max_residual = 0.0f;
  for (float r : host_residuals) {
    max_residual = std::max(max_residual, std::abs(r));
  }
  EXPECT_LT(max_residual, 1e-4f) << "Residuals should be near zero when rig "
                                    "transform composition is correct";
}

}  // namespace cunls
