/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES.
 * All rights reserved. SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <cuda_runtime.h>

#include <cstddef>
#include <unordered_map>
#include <vector>

#include "cunls/common/device_vector.h"
#include "cunls/common/types.h"
#include "cunls/minimizer/jacobian_mode.h"

namespace cunls {

class Problem;
class MinimizerState;

/**
 * @brief Builds finite-difference Jacobians for a residual batch, on the
 * manifold tangent space of each referenced state block.
 *
 * This is the numeric-diff counterpart to a FactorBatch's own analytic
 * `Evaluate(..., jacobians, ...)`: it fills the exact same dense per-factor
 * `ResidualsSize() x sum(StateBlockSizes())` row-major Jacobian layout
 * (`PerFactorJacobians`, see `cunls/common/types.h`), using only the factor
 * batch's residual-only evaluation (`FactorBatch::Evaluate` with
 * `jacobians == nullptr`) plus each referenced `StateBatch::Plus` for
 * manifold-correct perturbations. No per-factor-type code changes are
 * required.
 *
 * Perturbations are generated by perturbing one tangent coordinate of one
 * referenced state-block *position* at a time (shared across all factors in
 * the batch, since a residual batch's position `b` always refers to the same
 * `StateBatch` type), but multiple positions and dofs are perturbed and
 * evaluated with **no synchronization in between**: `Plus()` calls for
 * different (position, dof, sign) triples are spread across a small
 * `cudaStream_t` pool so they can overlap on the GPU, and the resulting
 * residual evaluations are queued back-to-back on the caller's stream with
 * no intervening `cudaStreamSynchronize` (only stream/event dependencies).
 * See `numeric_diff_jacobian.cu` for why this design does not batch all
 * perturbed evaluations into a single `FactorBatch::Evaluate` launch (as an
 * idealized design would): shipped factor batches (e.g.
 * `VectorBetweenFactorBatch`) bake their own `NumFactors()` into a stored
 * constructor member consumed directly by the underlying kernel launch, not
 * derived from the size of the `state_pointers`/`residuals` arrays passed to
 * `Evaluate`, so a generic wrapper cannot present a larger factor count to
 * an existing, unmodified factor batch's `Evaluate()` without also
 * replicating that factor batch's private per-factor data (e.g. between-
 * factor deltas), which requires factor-specific knowledge this class does
 * not have.
 *
 * Structural (factor, state-block-position) -> (state batch, block index)
 * resolution is precomputed once per residual batch (via `PrepareResidualBatch`,
 * called lazily by `Compute` on first use) from `Problem`'s host-side
 * pointer lists, and reused on every subsequent `Compute` call for that
 * residual batch -- it depends only on factor-graph connectivity, which is
 * static for the lifetime of a `Problem`/minimizer run.
 */
class NumericDiffJacobianBuilder {
 public:
  NumericDiffJacobianBuilder();
  ~NumericDiffJacobianBuilder();

  NumericDiffJacobianBuilder(const NumericDiffJacobianBuilder &) = delete;
  NumericDiffJacobianBuilder &operator=(const NumericDiffJacobianBuilder &) = delete;

  /**
   * @brief Precomputes the (factor, position) -> (state batch, block index)
   * mapping for one residual batch.
   *
   * Safe to call multiple times (e.g. if the problem structure changes);
   * cheap, host-only work. `Compute` calls this automatically the first time
   * it sees a given `residual_batch_index`, so most callers never need to
   * call this directly.
   *
   * @param problem The owning problem (must have both the residual batch and
   * all referenced state batches registered).
   * @param residual_batch_index Index into `problem.GetResidualBatches()`.
   */
  void PrepareResidualBatch(const Problem &problem, size_t residual_batch_index);

  /**
   * @brief Computes the numeric-diff Jacobian for one residual batch.
   *
   * @param stream CUDA stream on which the result becomes valid once all
   * work queued here (and on the internal stream pool) completes; safe to
   * enqueue further work depending on `jacobian_out` on this same stream
   * immediately after this call returns (no synchronize is performed here).
   * @param problem The owning problem.
   * @param residual_batch_index Index into `problem.GetResidualBatches()`.
   * @param minimizer_state Current minimizer state (source of the state
   * values being perturbed).
   * @param baseline_residuals Device pointer to the already-computed RAW
   * (pre-loss) residuals for this batch (`NumFactors() * ResidualsSize()`
   * floats), as produced by `FactorBatch::Evaluate(residuals, nullptr, ...)`.
   * Used directly for forward differencing; unused (but harmless if
   * provided) for central differencing.
   * @param jacobian_out Device pointer to this batch's dense per-factor
   * Jacobian output region (same layout `FactorBatch::Evaluate` would have
   * written).
   * @param options Finite-difference method and step size.
   */
  void Compute(cudaStream_t stream, const Problem &problem, size_t residual_batch_index,
              const MinimizerState &minimizer_state, const float *baseline_residuals,
              float *jacobian_out, const NumericDiffOptions &options);

 private:
  /** @brief Per-residual-batch structural perturbation plan (host-only). */
  struct BatchPlan {
    size_t num_factors = 0;
    size_t num_positions = 0;
    std::vector<size_t> state_block_sizes;   ///< Per position b.
    std::vector<size_t> col_offsets;         ///< Per position b, prefix sum of state_block_sizes.
    std::vector<size_t> owner_batch_index;   ///< Per position b: index into problem.GetStateBatches().
    std::vector<size_t> block_idx;           ///< Flattened [f * num_positions + b] -> block index within owner.
  };

  /**
   * @brief Per-residual-batch cached slot layout, device scratch, and
   * upload-validity bookkeeping.
   *
   * All of the host-built arrays this class uploads to the device each
   * `Compute` call (`delta`, the replicated state-pointer table, and the
   * differencing kernel's index/epsilon arrays) depend *only* on: (a) the
   * static factor-graph structure captured in `BatchPlan`, (b) `options`,
   * and (c) the *addresses* of the owning `StateBatch` buffers and of this
   * cache's own `x_plus_delta_scratch` allocation -- never on the current
   * state *values*, which are read directly on-device by `Plus`/`Evaluate`.
   * For a given `Problem`/minimizer run those addresses are stable across
   * `BuildSystem` calls (state buffers are value-copied in place, not
   * reallocated, once the minimizer's state snapshot is created), so this
   * cache lets every `Compute` call after the first skip all host-side
   * rebuilding and H2D uploads entirely, re-validated cheaply (a handful of
   * pointer comparisons) on every call in case that assumption ever doesn't
   * hold (e.g. structure changed via a fresh `PrepareResidualBatch`, or the
   * caller passed a `MinimizerState` backed by different buffers).
   */
  struct ComputeCache {
    bool uploaded = false;
    bool central = false;
    float step_size = 0.0f;
    size_t S = 0, W = 0, F = 0, P = 0;
    size_t residual_size = 0, total_cols = 0;
    size_t delta_total = 0, xpd_total = 0;

    // Host-side slot layout, built once per (plan, options) pair.
    std::vector<size_t> slot_b, slot_k, slot_owner;
    std::vector<float> slot_sign;
    std::vector<size_t> delta_offset, xpd_offset;
    std::vector<int> col_idx_h, plus_slot_h, minus_slot_h;
    std::vector<float> eps_h;

    // Address fingerprint of the last successful upload, used to cheaply
    // detect whether the cached device data is still valid.
    std::vector<const float *> last_owner_data_ptr;  // size P.
    const float *last_xpd_base = nullptr;

    // Per-residual-batch device scratch (never shared across residual
    // batches, so caching is always safe even when a Problem has several
    // numeric-diff residual batches evaluated back-to-back on one stream).
    dvector<float> delta_scratch;
    dvector<float> x_plus_delta_scratch;
    dvector<float> perturbed_residuals;
    dvector<const float *> state_pointer_scratch;
    dvector<int> col_idx_scratch;
    dvector<int> plus_slot_scratch;
    dvector<int> minus_slot_scratch;
    dvector<float> eps_scratch;
  };

  void EnsureStreamPool(size_t num_streams);

  std::unordered_map<size_t, BatchPlan> plans_;
  std::unordered_map<size_t, ComputeCache> caches_;

  std::vector<cudaStream_t> pool_streams_;
  std::vector<cudaEvent_t> pool_events_;
  cudaEvent_t delta_ready_event_ = nullptr;

  // Small pinned host staging buffers for the (now rare -- only on cache
  // rebuild) H2D uploads, reused/grown across calls; pageable
  // std::vector-backed uploads showed up as ~35x slower cudaMemcpyAsync
  // calls under nsys (internally staged through a driver bounce buffer).
  float *pinned_delta_host_ = nullptr;
  size_t pinned_delta_capacity_ = 0;
  const float **pinned_ptrs_host_ = nullptr;
  size_t pinned_ptrs_capacity_ = 0;
  int *pinned_int_host_ = nullptr;      // Holds col_idx/plus_slot/minus_slot back-to-back.
  size_t pinned_int_capacity_ = 0;
  float *pinned_eps_host_ = nullptr;
  size_t pinned_eps_capacity_ = 0;

  float *PinnedDeltaHost(size_t n);
  const float **PinnedPtrsHost(size_t n);
  int *PinnedIntHost(size_t n);
  float *PinnedEpsHost(size_t n);
};

}  // namespace cunls
